import type { TablerIconName } from '../ui/icon/tabler-icon.component';

export interface NavLink {
  label: string;
  description: string;
  path: string;
  roles: string[];
  icon: TablerIconName;
  group: string;
}

/**
 * Fuente de verdad de qué módulos ve cada rol en el sidebar (design-system /
 * Interaction Capability). Matriz documentada también en
 * `.specify/docs/architecture/module-map.md` § "Matriz rol → navegación UI".
 * Código canónico: este array.
 */
export const NAV_LINKS: NavLink[] = [
  {
    label: 'Prospectos',
    description: 'Listado y workpanel del pipeline comercial',
    path: '/ventas-crm/prospectos',
    roles: ['GerenteVentas', 'GerenteCuentasPublicas'],
    icon: 'list',
    group: 'Ventas CRM',
  },
  {
    label: 'Pipeline',
    description: 'Tablero por etapa del funnel comercial',
    path: '/ventas-crm/pipeline',
    roles: ['GerenteVentas', 'GerenteCuentasPublicas'],
    icon: 'dashboard',
    group: 'Ventas CRM',
  },
  {
    label: 'Entrada directa',
    description: 'Alta de cliente sin prospecto previo (solo Admin)',
    path: '/ventas-crm/entrada-directa',
    roles: ['Administrador'],
    icon: 'plus',
    group: 'Ventas CRM',
  },
  {
    label: 'Registrar accidente',
    description: 'Capturar un nuevo accidente en tiempo real',
    path: '/accidentes/registro',
    roles: ['Operador'],
    icon: 'car-crash',
    group: 'Emergencias',
  },
  {
    label: 'Lista de accidentes',
    description: 'Consultar y editar accidentes activos',
    path: '/accidentes/lista',
    roles: ['Operador', 'Tecnico'],
    icon: 'list',
    group: 'Emergencias',
  },
  {
    label: 'Calidad del registro',
    description: 'Completitud de campos críticos sobre el modelo analítico',
    path: '/emergencias/gestion/calidad',
    roles: ['DirectorOperaciones'],
    icon: 'chart-bar',
    group: 'Emergencias',
  },
  {
    label: 'Despacho (gestión)',
    description: 'Primer intento, desviación de llegada y capacidad del período',
    path: '/emergencias/gestion/despacho',
    roles: ['DirectorOperaciones'],
    icon: 'chart-bar',
    group: 'Emergencias',
  },
  {
    label: 'Evidencia y cierre',
    description: 'Cartera abierta, cobertura de evidencia y desenlace',
    path: '/emergencias/gestion/cierre',
    roles: ['DirectorOperaciones'],
    icon: 'chart-bar',
    group: 'Emergencias',
  },
  {
    label: 'Mi despacho',
    description: 'Despachos asignados a mi unidad',
    path: '/despacho/mi-despacho',
    roles: ['Unidad'],
    icon: 'radio',
    group: 'Despacho',
  },
  {
    label: 'Monitoreo de despacho',
    description: 'Asignación y seguimiento de unidades',
    path: '/despacho/monitoreo',
    roles: ['Operador', 'Despacho'],
    icon: 'radio',
    group: 'Despacho',
  },
  {
    label: 'Parámetros del algoritmo',
    description: 'Configuración del despacho inteligente',
    path: '/despacho/parametros',
    roles: ['DirectorTecnologico', 'Administrador'],
    icon: 'settings',
    group: 'Despacho',
  },
  {
    label: 'Mapa de seguimiento',
    description: 'Seguimiento GPS de unidades en curso',
    path: '/seguimiento/mapa',
    roles: ['Operador', 'Despacho'],
    icon: 'map',
    group: 'Seguimiento',
  },
  {
    label: 'Mi seguimiento',
    description: 'Seguimiento de mi despacho activo',
    path: '/seguimiento/mi-seguimiento',
    roles: ['Unidad'],
    icon: 'map',
    group: 'Seguimiento',
  },
  {
    label: 'Historial de emergencias',
    description: 'Casos cerrados y su expediente',
    path: '/seguimiento/historial',
    roles: ['Operador', 'Despacho'],
    icon: 'history',
    group: 'Seguimiento',
  },
  {
    label: 'Mis expedientes',
    description: 'Historial de casos como cliente',
    path: '/seguimiento/expedientes',
    roles: ['Cliente'],
    icon: 'history',
    group: 'Seguimiento',
  },
  {
    label: 'Disponibilidad de unidad',
    description: 'Marcar disponibilidad y ver flota',
    path: '/evidencia-unidad/disponibilidad',
    roles: ['Unidad'],
    icon: 'camera',
    group: 'Evidencia y flota',
  },
  {
    label: 'Flota',
    description: 'Administración de unidades de emergencia',
    path: '/evidencia-unidad/flota',
    roles: ['Despacho'],
    icon: 'camera',
    group: 'Evidencia y flota',
  },
  {
    label: 'Mis unidades',
    description: 'Alta, edición y baja de la flota del proveedor',
    path: '/red-operativa/alta-unidades/catalogo',
    roles: ['Cliente', 'Proveedor'],
    icon: 'car',
    group: 'Red operativa',
  },
  {
    label: 'Regiones operativas',
    description: 'Catálogo, validación y reevaluación de regiones',
    path: '/red-operativa/incorporacion-regional/catalogo',
    roles: ['DirectorTecnologico'],
    icon: 'map',
    group: 'Red operativa',
  },
  {
    label: 'Validación de región',
    description: 'Protocolo de onboarding y remediación de regiones',
    path: '/red-operativa/incorporacion-regional/validacion',
    roles: ['DirectorTecnologico'],
    icon: 'map-pin',
    group: 'Red operativa',
  },
  {
    label: 'Gestión de cuenta',
    description: 'Usuarios, roles y perfil corporativo de clientes',
    path: '/cuentas-clientes/gestion-cuenta',
    roles: ['Administrador'],
    icon: 'settings',
    group: 'Administración',
  },
  {
    label: 'Informes de cuentas',
    description: 'Listados tácticos de cuentas, incorporación, usuarios y accesos',
    path: '/cuentas-clientes/informes',
    // El Director Tecnológico ve el índice porque desde ahí llega a accesos
    // técnicos, el único que le corresponde; el índice le oculta los otros siete.
    roles: ['Administrador', 'DirectorTecnologico'],
    icon: 'chart-bar',
    group: 'Administración',
  },
  {
    label: 'Ciclo de vida',
    description: 'Churn por cohorte, ocupación y cuentas en riesgo',
    path: '/cuentas-clientes/gestion/ciclo',
    roles: ['DirectorCuentas'],
    icon: 'chart-bar',
    group: 'Administración',
  },
  {
    label: 'Incorporación de cuentas',
    description: 'Tiempo de alta, embudo y aprobación',
    path: '/cuentas-clientes/gestion/incorporacion',
    roles: ['DirectorCuentas'],
    icon: 'chart-bar',
    group: 'Administración',
  },
  {
    label: 'Acceso de cuentas',
    description: 'Concurrencia de sesiones y roles incompatibles',
    path: '/cuentas-clientes/gestion/acceso',
    roles: ['DirectorTecnologico'],
    icon: 'chart-bar',
    group: 'Administración',
  },
  {
    label: 'Informes comerciales',
    description: 'Prospectos, asignaciones, demos y notificaciones',
    // Los gerentes entran y el backend los acota a su cartera; `reasignaciones`
    // lo cierra su propio guard y el índice ni se lo ofrece.
    path: '/ventas-crm/informes',
    roles: ['DirectorMarketing', 'GerenteVentas', 'GerenteCuentasPublicas'],
    icon: 'chart-bar',
    group: 'Ventas CRM',
  },
  {
    label: 'Embudo comercial',
    description: 'Dónde se atasca y se pierde el pipeline',
    path: '/ventas-crm/gestion/embudo',
    roles: ['DirectorMarketing', 'GerenteVentas'],
    icon: 'chart-bar',
    group: 'Ventas CRM',
  },
  {
    label: 'Captación por canal',
    description: 'Volumen, conversión y convertidos por canal',
    path: '/ventas-crm/gestion/captacion',
    roles: ['DirectorMarketing', 'GerenteVentas'],
    icon: 'chart-bar',
    group: 'Ventas CRM',
  },
  {
    label: 'Nutrición del prospecto',
    description: 'Demo, avisos y efectividad de la nutrición',
    path: '/ventas-crm/gestion/nutricion',
    roles: ['DirectorMarketing', 'GerenteVentas'],
    icon: 'chart-bar',
    group: 'Ventas CRM',
  },
  {
    label: 'Informes de suscripciones',
    description: 'Suscripciones, facturas, cambios de plan y métodos de pago',
    // Cliente y Proveedor entran: ven **su** cuenta, y ahí es donde más importa
    // que vean su propia deuda.
    path: '/suscripciones/informes',
    roles: [
      'Administrador',
      'DirectorEstrategia',
      'DirectorFinanciero',
      'Cliente',
      'Proveedor',
    ],
    icon: 'chart-bar',
    group: 'Suscripciones',
  },
  {
    label: 'Cobro e ingreso',
    description: 'MRR, ingresos y si se cobra',
    path: '/suscripciones/gestion/cobro',
    roles: ['DirectorFinanciero'],
    icon: 'chart-bar',
    group: 'Suscripciones',
  },
  {
    label: 'Movimientos de cartera',
    description: 'NRR, upgrades y tiempo de resolución',
    path: '/suscripciones/gestion/movimientos',
    roles: ['DirectorFinanciero'],
    icon: 'chart-bar',
    group: 'Suscripciones',
  },
  {
    label: 'Catálogo y uso',
    description: 'Reparto de cartera y utilización de límites',
    path: '/suscripciones/gestion/catalogo',
    roles: ['DirectorEstrategia'],
    icon: 'chart-bar',
    group: 'Suscripciones',
  },
  {
    label: 'Informes de red',
    description: 'Flota, bajas, regiones y validaciones',
    path: '/red-operativa/informes',
    roles: [
      'DirectorExpansion',
      'DirectorTecnologico',
      'Cliente',
      'Proveedor',
    ],
    icon: 'chart-bar',
    group: 'Red operativa',
  },
  {
    label: 'Flota y cobertura',
    description: 'Estado de la flota y condados en cobertura crítica',
    path: '/red-operativa/gestion/flota',
    roles: ['DirectorExpansion'],
    icon: 'chart-bar',
    group: 'Red operativa',
  },
  {
    label: 'Mercados y retirada',
    description: 'Apertura de regiones y mercados en riesgo',
    path: '/red-operativa/gestion/mercados',
    roles: ['DirectorExpansion'],
    icon: 'chart-bar',
    group: 'Red operativa',
  },
  {
    label: 'Criterios de validación',
    description: 'Aprobación al primer intento y motivos de rechazo',
    path: '/red-operativa/gestion/validacion',
    roles: ['DirectorTecnologico'],
    icon: 'chart-bar',
    group: 'Red operativa',
  },
  {
    label: 'Informes de casos',
    description: 'Casos, despachos, evidencia y cierres',
    // El Cliente entra: ve los casos **cerrados de sus zonas contratadas**, y el
    // aviso de alcance de la respuesta se lo dice. Los otros cuatro los filtra
    // el índice y los cierra el guard interno.
    //
    // ⚠️ `PartnerIntegracion` **no está**: su acceso a estos datos tiene su
    // propio camino, con su alcance y su auditoría.
    path: '/emergencias/informes-simples',
    roles: ['Operador', 'Tecnico', 'Administrador', 'DirectorOperaciones', 'Cliente'],
    icon: 'chart-bar',
    group: 'Emergencias',
  },
  {
    label: 'Informes de soporte',
    description: 'Cola de tickets y escalados del período',
    // El Cliente entra: ve **sus** tickets, y el aviso de alcance de la
    // respuesta se lo dice. Los escalados los filtra el índice y los cierra su
    // propio guard.
    //
    // ⚠️ `PartnerIntegracion` **no está aquí**, y no es un descuido: FR-UI-033
    // dice que la consola de Partners y su portal no se fusionan, y que ningún
    // rol descubre la existencia del otro departamento. Darle una entrada en el
    // grupo «Soporte» rompería esa regla.
    //
    // El backend **sí** le permite el listado —puede abrir una disputa de
    // facturación, y ve solo sus tickets—, así que la ruta le responde si llega
    // a ella. Lo que no tiene es un enlace. Queda anotado como decisión de
    // producto, no resuelto por conveniencia.
    path: '/soporte-cliente/informes',
    roles: [
      'Soporte',
      'Administrador',
      'DesarrolladorAPIs',
      'DirectorTecnologico',
      'GerenteExitoCliente',
      'Cliente',
    ],
    icon: 'chart-bar',
    group: 'Soporte',
  },
  {
    label: 'Cumplimiento de SLA',
    description: 'Indicador BSC y cobertura de compromiso',
    path: '/soporte-cliente/gestion/cumplimiento',
    roles: ['GerenteExitoCliente', 'Soporte'],
    icon: 'chart-bar',
    group: 'Soporte',
  },
  {
    label: 'Cola en curso',
    description: 'Tablero de cola con corte temporal',
    path: '/soporte-cliente/gestion/cola',
    roles: ['GerenteExitoCliente', 'Soporte'],
    icon: 'chart-bar',
    group: 'Soporte',
  },
  {
    label: 'Tendencias',
    description: 'Carga diaria y reincidencia',
    path: '/soporte-cliente/gestion/tendencias',
    roles: ['GerenteExitoCliente', 'Soporte'],
    icon: 'chart-bar',
    group: 'Soporte',
  },
  {
    label: 'Solicitudes de cliente',
    description: 'Aprobar, rechazar o anular autorregistros',
    path: '/cuentas-clientes/incorporacion-clientes/solicitudes',
    roles: ['Administrador'],
    icon: 'list',
    group: 'Administración',
  },
  {
    label: 'Mis tickets',
    description: 'Reportar y dar seguimiento a incidencias',
    path: '/soporte-cliente/mis-tickets',
    roles: ['Cliente'],
    icon: 'list',
    group: 'Soporte',
  },
  {
    label: 'Cola de soporte',
    description: 'Tickets pendientes de atención',
    path: '/soporte-cliente/cola',
    roles: ['Soporte', 'DesarrolladorAPIs', 'DirectorTecnologico'],
    icon: 'list',
    group: 'Soporte',
  },
  {
    label: 'Dashboard de soporte',
    description: 'Métricas de tickets y cumplimiento de SLA',
    path: '/soporte-cliente/dashboard',
    roles: ['Soporte', 'DesarrolladorAPIs', 'DirectorTecnologico'],
    icon: 'dashboard',
    group: 'Soporte',
  },
  {
    label: 'Configuración de SLA',
    description: 'Reglas de tiempos de respuesta y resolución por plan',
    path: '/soporte-cliente/configuracion-sla',
    roles: ['Administrador'],
    icon: 'settings',
    group: 'Soporte',
  },
  {
    label: 'Mi suscripción',
    description: 'Estado del plan, acceso y cancelación',
    path: '/suscripciones/mi-suscripcion',
    roles: ['Cliente', 'Proveedor'],
    icon: 'history',
    group: 'Suscripciones',
  },
  {
    label: 'Métodos de pago',
    description: 'Registrar o actualizar medio de cobro',
    path: '/suscripciones/metodos-pago',
    roles: ['Cliente', 'Proveedor'],
    icon: 'settings',
    group: 'Suscripciones',
  },
  {
    label: 'Historial de facturas',
    description: 'Consultar facturas emitidas y cobros',
    path: '/suscripciones/historial-facturas',
    roles: ['Cliente', 'Proveedor'],
    icon: 'list',
    group: 'Suscripciones',
  },
  {
    label: 'Cambio de plan',
    description: 'Solicitar upgrade o downgrade de suscripción',
    path: '/suscripciones/cambio-plan',
    roles: ['Cliente', 'Proveedor'],
    icon: 'refresh',
    group: 'Suscripciones',
  },
  {
    label: 'Catálogo de planes',
    description: 'Ver planes activos y límites',
    path: '/suscripciones/catalogo-planes',
    roles: ['Cliente', 'Proveedor', 'Administrador', 'DirectorEstrategia'],
    icon: 'dashboard',
    group: 'Suscripciones',
  },
  {
    label: 'Aprobaciones de plan',
    description: 'Aprobar o rechazar downgrades pendientes',
    path: '/suscripciones/aprobaciones-downgrade',
    roles: ['Administrador'],
    icon: 'circle-check',
    group: 'Suscripciones',
  },

  // --- Partners y API ---
  // Dos superficies de departamentos distintos: los sidebars NO se fusionan
  // (design-system § 5). El partner nunca ve la consola y viceversa.
  {
    label: 'Partners',
    description: 'Incorporar partners y asignarles su plan de acceso',
    path: '/partners/consola',
    roles: ['Administrador', 'DesarrolladorAPIs'],
    icon: 'license',
    group: 'Partners y API',
  },
  {
    label: 'Solicitudes pendientes',
    description: 'Aprobar o rechazar el paso a producción',
    path: '/partners/consola/solicitudes',
    roles: ['Administrador', 'DesarrolladorAPIs'],
    icon: 'clock',
    group: 'Partners y API',
  },
  {
    label: 'Mi integración',
    description: 'Tu estado, tu cupo y tus credenciales de API',
    path: '/partners/portal',
    roles: ['PartnerIntegracion'],
    icon: 'key',
    group: 'Partners y API',
  },
  {
    label: 'Informes de partners',
    description: 'Partners, credenciales, bitácora, contrato y alcance',
    path: '/partners/informes',
    roles: ['Administrador', 'DesarrolladorAPIs', 'DirectorTecnologico'],
    icon: 'chart-bar',
    group: 'Partners y API',
  },
  {
    label: 'Consumo de la API',
    description: 'Latencia p95, errores y comparativa entre partners',
    path: '/partners/gestion/consumo',
    roles: ['DirectorTecnologico'],
    icon: 'chart-bar',
    group: 'Partners y API',
  },
  {
    label: 'Incorporación',
    description: 'Versiones, credenciales inactivas y tiempo hasta producción',
    path: '/partners/gestion/incorporacion',
    roles: ['DirectorTecnologico'],
    icon: 'chart-bar',
    group: 'Partners y API',
  },
  {
    label: 'Entrega contratada',
    description: 'Clientes con integración activa y canales de entrega',
    path: '/partners/gestion/entrega',
    roles: ['DirectorTecnologico'],
    icon: 'chart-bar',
    group: 'Partners y API',
  },
  {
    label: 'Estado de mi acceso',
    description: 'Tus partners, tus credenciales y los cambios de tu acceso',
    path: '/partners/informes',
    roles: ['PartnerIntegracion'],
    icon: 'chart-bar',
    group: 'Partners y API',
  },
  {
    label: 'Registros de API',
    description: 'Detalle de cada llamada, con filtros y autodiagnóstico',
    path: '/partners/consola/logs',
    roles: ['Administrador', 'DesarrolladorAPIs'],
    icon: 'list',
    group: 'Partners y API',
  },
  {
    label: 'Reporte de consumo',
    description: 'Consumo mensual, comparable entre períodos',
    path: '/partners/consola/reportes',
    roles: ['Administrador', 'DesarrolladorAPIs'],
    icon: 'chart-bar',
    group: 'Partners y API',
  },
  {
    // Solo Administrador: es una cola de decisiones de negocio, no de
    // plataforma. El DesarrolladorAPIs no la ve en su sidebar.
    label: 'Excepciones de facturación',
    description: 'Excedente que no se pudo facturar y espera acción',
    path: '/partners/consola/excepciones',
    roles: ['Administrador'],
    icon: 'report-money',
    group: 'Partners y API',
  },
  {
    // Solo Administrador: la reactivación de un partner es competencia suya
    // (RN-PAC-009) y el sistema nunca la ejecuta por su cuenta.
    label: 'Suspensiones de partners',
    description: 'Suspendidos y en mora; suspender y reactivar',
    path: '/partners/consola/suspensiones',
    roles: ['Administrador'],
    icon: 'license',
    group: 'Partners y API',
  },
  {
    label: 'Ingreso recurrente',
    description: 'MRR, ARR y renovación de la empresa (OE1)',
    path: '/estrategico/oe1/ingreso',
    roles: ['DirectorFinanciero', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Cartera',
    description: 'Mezcla por plan y segmento por tipo (OE1)',
    path: '/estrategico/oe1/cartera',
    roles: ['DirectorEstrategia', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Captación',
    description: 'Embudo digital y velocidad del ciclo (OE1)',
    path: '/estrategico/oe1/captacion',
    roles: ['DirectorMarketing', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Ciclo de vida',
    description: 'Churn y onboarding de la empresa (OE1)',
    path: '/estrategico/oe1/ciclo',
    roles: ['Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Servicio (SLA)',
    description: 'Cumplimiento de compromiso de tiempo (OE5)',
    path: '/estrategico/oe5/servicio',
    roles: ['GerenteExitoCliente', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Ingresos retenidos',
    description: 'NRR descompuesto: expansión, contracción y churn (OE5)',
    path: '/estrategico/oe5/ingresos',
    roles: ['DirectorFinanciero', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Planes y antigüedad',
    description: 'SLA por plan, movimientos aprobados y cuentas activas (OE5)',
    path: '/estrategico/oe5/planes',
    roles: ['DirectorEstrategia', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Cuentas en riesgo',
    description: 'Cruce de señales de churn; solo Gerente (OE5)',
    path: '/estrategico/oe5/riesgo',
    roles: ['Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Llegada',
    description: 'Mediana y p95 de respuesta (OE6)',
    path: '/estrategico/oe6/llegada',
    roles: ['DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Diagnóstico de tiempos',
    description: 'Tramos del ciclo vs histórico (OE6)',
    path: '/estrategico/oe6/diagnostico',
    roles: ['DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Ejecución del despacho',
    description: 'Rechazos, abortos y cierres forzados (OE6)',
    path: '/estrategico/oe6/ejecucion',
    roles: ['DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Personas atendidas',
    description: 'Impacto humano y evidencia (OE6)',
    path: '/estrategico/oe6/personas',
    roles: ['DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Latencia de despacho',
    description: 'p95 registro→asignación (OE3)',
    path: '/estrategico/oe3/latencia',
    roles: ['DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Calidad del despacho',
    description: 'Error de registro y primer intento (OE3)',
    path: '/estrategico/oe3/calidad',
    roles: ['DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Capacidad por condado',
    description: 'Demanda vs flota del período (OE3)',
    path: '/estrategico/oe3/capacidad',
    roles: ['DirectorExpansion', 'DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Respaldo vecinal',
    description: 'Vecinos con unidad disponible (OE3)',
    path: '/estrategico/oe3/respaldo',
    roles: ['DirectorExpansion', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Calidad del histórico',
    description: 'Índice y huecos del registro (OE4)',
    path: '/estrategico/oe4/calidad',
    roles: ['DirectorDatos', 'DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Concentración',
    description: 'Ranking de zonas por nombre, no mapa (OE4)',
    path: '/estrategico/oe4/concentracion',
    roles: ['DirectorDatos', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Impacto',
    description: 'Víctimas y vía con denominadores reales (OE4)',
    path: '/estrategico/oe4/impacto',
    roles: ['DirectorDatos', 'DirectorOperaciones', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Cobertura del histórico',
    description: 'Masa crítica por condado (OE4)',
    path: '/estrategico/oe4/cobertura',
    roles: ['DirectorDatos', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Uso de la API',
    description: 'Adopción, errores y latencia del ecosistema (OE2)',
    path: '/estrategico/oe2/uso',
    roles: ['DirectorTecnologico', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Dinero de la API',
    description: 'Excedente facturable y peso de la API (OE2)',
    path: '/estrategico/oe2/dinero',
    roles: ['DirectorTecnologico', 'Gerente', 'DirectorFinanciero'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Ecosistema',
    description: 'Versiones, comparativa y crecimiento (OE2)',
    path: '/estrategico/oe2/ecosistema',
    roles: ['DirectorTecnologico', 'Gerente'],
    icon: 'chart-bar',
    group: 'Estratégico',
  },
  {
    label: 'Mi consumo',
    description: 'Tu consumo del período y tu excedente estimado',
    path: '/partners/portal/consumo',
    roles: ['PartnerIntegracion'],
    icon: 'chart-bar',
    group: 'Partners y API',
  },
  {
    label: 'Contrato de integración',
    description: 'Versión vigente y versiones soportadas por servicio',
    path: '/partners/portal/contrato',
    roles: ['PartnerIntegracion'],
    icon: 'license',
    group: 'Partners y API',
  },
  {
    // Misma pantalla que "Mis tickets" del Cliente, pero **dentro del portal del
    // partner**: el backend lo reconoce como reportador (`ROLES_REPORTADORES`,
    // RF-O83.2) y podía disputar su factura, pero no tenía por dónde entrar
    // (hallazgo #18 de la revisión del 24/08/2026).
    //
    // No se añade `PartnerIntegracion` a la entrada del grupo "Soporte": FR-UI-033
    // exige que cada rol vea su sidebar íntegro sin descubrir la existencia de
    // otro departamento, y eso le habría abierto un grupo ajeno.
    label: 'Mis tickets',
    description: 'Reportar incidencias y disputar cargos de tu integración',
    path: '/soporte-cliente/mis-tickets',
    roles: ['PartnerIntegracion'],
    icon: 'list',
    group: 'Partners y API',
  },
];
