"""Domain constants for accident lifecycle."""

ESTADO_BORRADOR = "BORRADOR"
ESTADO_REPORTADO = "REPORTADO"
ESTADO_BUSCANDO_UNIDAD = "BUSCANDO_UNIDAD"
ESTADO_ASIGNADO = "ASIGNADO"
ESTADO_EN_ATENCION = "EN_ATENCIÓN"
ESTADO_CERRADO = "CERRADO"
ESTADO_DESCARTADO = "DESCARTADO"
ESTADO_FUSIONADO = "FUSIONADO"

DUPLICATE_RADIUS_METERS = 50
DUPLICATE_WINDOW_MS = 5 * 60 * 1000
RETROSPECTIVE_WINDOW_MS = 24 * 60 * 60 * 1000
