from django.urls import path

from apps.informes_tacticos.views.compuestos_views import (
    IndiceCalidadView,
    PerdidaSenalView,
    RendimientoProveedorView,
)
from apps.informes_tacticos.views.despacho_views import (
    AsignacionAutomaticaVsManualView,
    CargaPorUnidadView,
    RatioDemandaCapacidadView,
    RechazoTimeoutPorUnidadView,
    TiempoReportadoConfirmadoView,
    TiempoRespuestaPorSeveridadView,
)
from apps.informes_tacticos.views.registro_views import (
    CompletitudCamposCriticosView,
    DescarteFusionView,
    DistribucionSeveridadView,
    DistribucionZonaView,
    ImpactoHumanoView,
    RankingUbicacionesView,
    VolumenCasosView,
)
from apps.informes_tacticos.views.seguimiento_views import (
    AbortosPerdidasView,
    CierresForzadosView,
    TiempoAsignadoCerradoView,
)

urlpatterns = [
    path(
        "informes-tacticos/registro/volumen-casos",
        VolumenCasosView.as_view(),
        name="informes-tacticos-registro-volumen-casos",
    ),
    path(
        "informes-tacticos/registro/distribucion-severidad",
        DistribucionSeveridadView.as_view(),
        name="informes-tacticos-registro-distribucion-severidad",
    ),
    path(
        "informes-tacticos/registro/distribucion-zona",
        DistribucionZonaView.as_view(),
        name="informes-tacticos-registro-distribucion-zona",
    ),
    path(
        "informes-tacticos/registro/completitud-campos-criticos",
        CompletitudCamposCriticosView.as_view(),
        name="informes-tacticos-registro-completitud-campos-criticos",
    ),
    path(
        "informes-tacticos/registro/descarte-fusion",
        DescarteFusionView.as_view(),
        name="informes-tacticos-registro-descarte-fusion",
    ),
    path(
        "informes-tacticos/registro/ranking-ubicaciones",
        RankingUbicacionesView.as_view(),
        name="informes-tacticos-registro-ranking-ubicaciones",
    ),
    path(
        "informes-tacticos/registro/impacto-humano",
        ImpactoHumanoView.as_view(),
        name="informes-tacticos-registro-impacto-humano",
    ),
    path(
        "informes-tacticos/despacho/asignacion-automatica-vs-manual",
        AsignacionAutomaticaVsManualView.as_view(),
        name="informes-tacticos-despacho-asignacion-automatica-vs-manual",
    ),
    path(
        "informes-tacticos/despacho/tiempo-reportado-confirmado",
        TiempoReportadoConfirmadoView.as_view(),
        name="informes-tacticos-despacho-tiempo-reportado-confirmado",
    ),
    path(
        "informes-tacticos/despacho/tiempo-respuesta-por-severidad",
        TiempoRespuestaPorSeveridadView.as_view(),
        name="informes-tacticos-despacho-tiempo-respuesta-por-severidad",
    ),
    path(
        "informes-tacticos/despacho/rechazo-timeout-por-unidad",
        RechazoTimeoutPorUnidadView.as_view(),
        name="informes-tacticos-despacho-rechazo-timeout-por-unidad",
    ),
    path(
        "informes-tacticos/despacho/carga-por-unidad",
        CargaPorUnidadView.as_view(),
        name="informes-tacticos-despacho-carga-por-unidad",
    ),
    path(
        "informes-tacticos/despacho/ratio-demanda-capacidad",
        RatioDemandaCapacidadView.as_view(),
        name="informes-tacticos-despacho-ratio-demanda-capacidad",
    ),
    path(
        "informes-tacticos/seguimiento/tiempo-asignado-cerrado",
        TiempoAsignadoCerradoView.as_view(),
        name="informes-tacticos-seguimiento-tiempo-asignado-cerrado",
    ),
    path(
        "informes-tacticos/seguimiento/cierres-forzados",
        CierresForzadosView.as_view(),
        name="informes-tacticos-seguimiento-cierres-forzados",
    ),
    path(
        "informes-tacticos/seguimiento/abortos-perdidas",
        AbortosPerdidasView.as_view(),
        name="informes-tacticos-seguimiento-abortos-perdidas",
    ),
    path(
        "informes-tacticos/compuestos/perdida-senal",
        PerdidaSenalView.as_view(),
        name="informes-tacticos-compuestos-perdida-senal",
    ),
    path(
        "informes-tacticos/compuestos/indice-calidad",
        IndiceCalidadView.as_view(),
        name="informes-tacticos-compuestos-indice-calidad",
    ),
    path(
        "informes-tacticos/compuestos/rendimiento-proveedor",
        RendimientoProveedorView.as_view(),
        name="informes-tacticos-compuestos-rendimiento-proveedor",
    ),
]
